/**
 * Style Dictionary 5.x build pipeline — DTCG tokens → CSS / JSON / Tailwind.
 *
 * CDC ref : F-005 (Style Dictionary build pipeline)
 * Brick   : B-006
 * Risk    : Tooling 60% (build-time artifact, no runtime user impact).
 *
 * Responsibilities :
 *   - Accept the DTCG `morphicTokens` tree (from tokens.ts — single source of truth).
 *   - Produce 3 outputs via Style Dictionary 5.4.1:
 *       1. `morphic.css`          — CSS custom properties under `:root`, prefix `--morphic-*`.
 *       2. `morphic.json`         — flat JSON for design tools.
 *       3. `morphic.tailwind.js`  — ESM module exporting nested object for Tailwind `theme.extend`.
 *   - Pure module : no DOM, no side effects until `buildMorphicTokens()` is called.
 *
 * Defensive contracts :
 *   - `usesDtcg: true` is non-optional — the token tree uses W3C 2025.10 DTCG syntax.
 *   - All platforms use the caller-provided `outDir` (no hard-coded paths — testable).
 *   - The custom `javascript/tailwind` format produces valid ESM and matches the
 *     DTCG axis hierarchy exactly.
 */

import StyleDictionary from 'style-dictionary';
import type { Config, FormatFnArguments } from 'style-dictionary/types';
import { CONTRASTS, DENSITIES, FONT_SIZES, MOTIONS, morphicTokens, THEMES } from './tokens.js';

// Re-export axis constants for tests + downstream consumers.
export { CONTRASTS, DENSITIES, FONT_SIZES, MOTIONS, THEMES };

/**
 * Build the Style Dictionary configuration for the morphic token pipeline.
 *
 * Returns a deterministic, pure config — same input `outDir` always yields the
 * same shape. Callers may inspect this config without triggering any I/O.
 */
export function getStyleDictionaryConfig(outDir: string): Config {
  const buildPath = `${outDir}/`;
  return {
    usesDtcg: true,
    tokens: morphicTokens,
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath,
        files: [
          {
            destination: 'morphic.css',
            format: 'css/variables',
            options: { outputReferences: false },
          },
        ],
      },
      json: {
        transformGroup: 'js',
        buildPath,
        files: [
          {
            destination: 'morphic.json',
            format: 'json/flat',
          },
        ],
      },
      tailwind: {
        transformGroup: 'js',
        buildPath,
        files: [
          {
            destination: 'morphic.tailwind.js',
            format: 'javascript/tailwind',
          },
        ],
      },
    },
  };
}

/**
 * Custom Style Dictionary format — emits a Tailwind-ready ESM module.
 *
 * Output shape :
 * ```js
 * export default {
 *   morphic: {
 *     theme: { light: "light", dark: "dark", ... },
 *     motion: { full: "full", reduced: "reduced", ... },
 *     ...
 *   }
 * };
 * ```
 *
 * Consumers wire it into `tailwind.config.ts`:
 * ```ts
 * import morphic from '@shinkofa/morphic-engine/dist/tokens/morphic.tailwind.js';
 * export default { theme: { extend: morphic } };
 * ```
 */
function tailwindFormat({ dictionary }: FormatFnArguments): string {
  const tree: Record<string, Record<string, string>> = {};
  for (const token of dictionary.allTokens) {
    const [namespace, axis, value] = token.path;
    if (namespace !== 'morphic' || !axis || !value) continue;
    tree[axis] ??= {};
    tree[axis][value] = String(token.$value ?? token.value);
  }
  const body = JSON.stringify({ morphic: tree }, null, 2);
  return `// Auto-generated by @shinkofa/morphic-engine — DO NOT EDIT.\nexport default ${body};\n`;
}

/**
 * Run the Style Dictionary build pipeline.
 *
 * Writes 3 files to `outDir` :
 *   - `morphic.css`
 *   - `morphic.json`
 *   - `morphic.tailwind.js`
 *
 * Idempotent — same input produces byte-identical output across runs.
 */
export async function buildMorphicTokens(outDir: string): Promise<void> {
  const sd = new StyleDictionary(getStyleDictionaryConfig(outDir));
  sd.registerFormat({ name: 'javascript/tailwind', format: tailwindFormat });
  await sd.buildAllPlatforms();
}
