/**
 * Style Dictionary 5.x build pipeline — DTCG tokens → CSS / JSON / Tailwind.
 *
 * CDC ref : F-005 (Style Dictionary build pipeline)
 * Brick   : B-006
 * Risk    : Tooling 60% (build-time artifact, no runtime user impact).
 *
 * Responsibilities :
 *   - Accept the DTCG `morphicTokens` tree (from tokens.ts — single source of truth).
 *   - Produce 3 outputs via Style Dictionary 5.4.1:
 *       1. `morphic.css`          — CSS custom properties under `:root`, prefix `--morphic-*`.
 *       2. `morphic.json`         — flat JSON for design tools.
 *       3. `morphic.tailwind.js`  — ESM module exporting nested object for Tailwind `theme.extend`.
 *   - Pure module : no DOM, no side effects until `buildMorphicTokens()` is called.
 *
 * Defensive contracts :
 *   - `usesDtcg: true` is non-optional — the token tree uses W3C 2025.10 DTCG syntax.
 *   - All platforms use the caller-provided `outDir` (no hard-coded paths — testable).
 *   - The custom `javascript/tailwind` format produces valid ESM and matches the
 *     DTCG axis hierarchy exactly.
 */

import StyleDictionary from 'style-dictionary';
import type { Config, FormatFnArguments } from 'style-dictionary/types';
import {
  CONTRASTS,
  DENSITIES,
  FONT_FAMILIES,
  FONT_SIZES,
  MOTIONS,
  morphicTokens,
  THEMES,
} from './tokens.js';

// Re-export axis constants for tests + downstream consumers.
export { CONTRASTS, DENSITIES, FONT_FAMILIES, FONT_SIZES, MOTIONS, THEMES };

/**
 * Build the Style Dictionary configuration for the morphic token pipeline.
 *
 * Returns a deterministic, pure config — same input `outDir` always yields the
 * same shape. Callers may inspect this config without triggering any I/O.
 */
export function getStyleDictionaryConfig(outDir: string, kotlinOutDir: string = outDir): Config {
  const buildPath = `${outDir}/`;
  return {
    usesDtcg: true,
    tokens: morphicTokens,
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath,
        files: [
          {
            destination: 'morphic.css',
            format: 'css/variables',
            options: { outputReferences: false },
          },
        ],
      },
      json: {
        transformGroup: 'js',
        buildPath,
        files: [
          {
            destination: 'morphic.json',
            format: 'json/flat',
          },
        ],
      },
      tailwind: {
        transformGroup: 'js',
        buildPath,
        files: [
          {
            destination: 'morphic.tailwind.js',
            format: 'javascript/tailwind',
          },
        ],
      },
      // Android target (A-1). Routed to its own buildPath so the generated
      // Kotlin file can land directly in the `android/` subtree while the web
      // outputs stay on the primary outDir. Defaults to outDir for single-dir
      // test runs.
      kotlin: {
        transformGroup: 'js',
        buildPath: `${kotlinOutDir}/`,
        files: [
          {
            destination: 'MorphicTokens.kt',
            format: 'kotlin/object',
          },
        ],
      },
    },
  };
}

/**
 * Custom Style Dictionary format — emits a Tailwind-ready ESM module.
 *
 * Output shape :
 * ```js
 * export default {
 *   morphic: {
 *     theme: { light: "light", dark: "dark", ... },
 *     motion: { full: "full", reduced: "reduced", ... },
 *     ...
 *   }
 * };
 * ```
 *
 * Consumers wire it into `tailwind.config.ts`:
 * ```ts
 * import morphic from '@theermite/morphic-engine/dist/tokens/morphic.tailwind.js';
 * export default { theme: { extend: morphic } };
 * ```
 */
function tailwindFormat({ dictionary }: FormatFnArguments): string {
  const tree: Record<string, Record<string, string>> = {};
  for (const token of dictionary.allTokens) {
    const [namespace, axis, value] = token.path;
    if (namespace !== 'morphic' || !axis || !value) continue;
    tree[axis] ??= {};
    tree[axis][value] = String(token.$value ?? token.value);
  }
  const body = JSON.stringify({ morphic: tree }, null, 2);
  return `// Auto-generated by @theermite/morphic-engine — DO NOT EDIT.\nexport default ${body};\n`;
}

/** Token enum value (`high-contrast`) → Kotlin const name (`HIGH_CONTRAST`). */
function toKotlinConst(value: string): string {
  return value.toUpperCase().replace(/-/g, '_');
}

/** Token axis (`fontSize`) → Kotlin nested-object name (`FontSize`). */
function toKotlinObject(axis: string): string {
  return axis.charAt(0).toUpperCase() + axis.slice(1);
}

/**
 * Custom Style Dictionary format — emits a pure-Kotlin token object (A-1).
 *
 * The built-in `compose/object` format wraps values in `Color(0xFF…)` / `.dp`
 * / `.sp` — designed for color and dimension tokens. The morphic axes are
 * string enums (`light`, `reduced`, …), so a string-valued object is the
 * correct shape. Output :
 * ```kotlin
 * object MorphicTokens {
 *   object Theme {
 *     const val LIGHT = "light"
 *     val all = listOf(LIGHT, ...)
 *   }
 * }
 * ```
 * `const val` makes each value directly consumable by the A-2 sensory enums;
 * `all` is the closed-set basis for enum validation. Deterministic iteration
 * over `dictionary.allTokens` guarantees byte-identical output across runs.
 */
function kotlinFormat({ dictionary }: FormatFnArguments): string {
  const axes = new Map<string, string[]>();
  for (const token of dictionary.allTokens) {
    const [namespace, axis, value] = token.path;
    if (namespace !== 'morphic' || !axis || !value) continue;
    const values = axes.get(axis) ?? [];
    values.push(String(token.$value ?? token.value));
    axes.set(axis, values);
  }

  const blocks: string[] = [];
  for (const [axis, values] of axes) {
    const consts = values.map((v) => `        const val ${toKotlinConst(v)} = "${v}"`).join('\n');
    const all = `        val all = listOf(${values.map(toKotlinConst).join(', ')})`;
    blocks.push(`    object ${toKotlinObject(axis)} {\n${consts}\n${all}\n    }`);
  }

  const header =
    '// Auto-generated by @theermite/morphic-engine — DO NOT EDIT.\n' +
    '// Source of truth: packages/engine/src/tokens.ts (DTCG).\n' +
    '// Regenerate via: node scripts/gen-android-tokens.mjs';
  return `${header}\npackage com.theermite.morphic.tokens\n\nobject MorphicTokens {\n${blocks.join('\n\n')}\n}\n`;
}

/**
 * Run the Style Dictionary build pipeline.
 *
 * Writes 3 web files to `outDir` :
 *   - `morphic.css`
 *   - `morphic.json`
 *   - `morphic.tailwind.js`
 *
 * Writes 1 Android file to `kotlinOutDir` (defaults to `outDir`) :
 *   - `MorphicTokens.kt`
 *
 * `kotlinOutDir` lets the generator route the Kotlin output into the `android/`
 * subtree while keeping the web artifacts on the primary dir (A-1).
 *
 * Idempotent — same input produces byte-identical output across runs.
 */
export async function buildMorphicTokens(
  outDir: string,
  kotlinOutDir: string = outDir,
): Promise<void> {
  const sd = new StyleDictionary(getStyleDictionaryConfig(outDir, kotlinOutDir));
  sd.registerFormat({ name: 'javascript/tailwind', format: tailwindFormat });
  sd.registerFormat({ name: 'kotlin/object', format: kotlinFormat });
  await sd.buildAllPlatforms();
}
