// Auto-generated by @theermite/morphic-engine — DO NOT EDIT.
// Source of truth: packages/engine/src/tokens.ts (DTCG).
// Regenerate via: node scripts/gen-android-tokens.mjs
package com.theermite.morphic.tokens

object MorphicTokens {
    object Theme {
        const val LIGHT = "light"
        const val DARK = "dark"
        const val AUTO = "auto"
        const val HIGH_CONTRAST = "high-contrast"
        const val SEPIA = "sepia"
        val all = listOf(LIGHT, DARK, AUTO, HIGH_CONTRAST, SEPIA)
    }

    object Motion {
        const val FULL = "full"
        const val REDUCED = "reduced"
        const val NONE = "none"
        val all = listOf(FULL, REDUCED, NONE)
    }

    object Contrast {
        const val NO_PREFERENCE = "no-preference"
        const val MORE = "more"
        const val LESS = "less"
        const val CUSTOM = "custom"
        val all = listOf(NO_PREFERENCE, MORE, LESS, CUSTOM)
    }

    object Density {
        const val COMPACT = "compact"
        const val COMFORTABLE = "comfortable"
        const val SPACIOUS = "spacious"
        val all = listOf(COMPACT, COMFORTABLE, SPACIOUS)
    }

    object FontSize {
        const val SM = "sm"
        const val MD = "md"
        const val LG = "lg"
        const val XL = "xl"
        val all = listOf(SM, MD, LG, XL)
    }

    object FontFamily {
        const val SYSTEM = "system"
        const val SERIF = "serif"
        const val ATKINSON = "atkinson"
        const val DYSLEXIC = "dyslexic"
        val all = listOf(SYSTEM, SERIF, ATKINSON, DYSLEXIC)
    }
}
